### ISSUE TITLE
alamode and phonopy-ALM interface

### ISSUE THREAD

**Issue by akentphonon** [ttadano/ALM#33]
Dear Dr. Tadano, and Dr. Togo

Not sure if this the right place for this.

I have been trying to use phonopy-alm interface to fit force-constants within ALM and trasnlate them back to phonopy. I am using phonopy ALM python library for this as API.

I did two test
(1) Fit the force constants within alamode (alm part of alamode) using the force and displacement and generated dispersion within anphonon i got good expected results. This is shown as Alamode (blue lines)

(2) When i use phonopy-ALM interface the dispersion is bit different... These are magneta line

This is shown in the attached plot.
![Alamode-phonopy-ALM-comparsion](https://user-images.githubusercontent.com/59974303/76882395-e1b11880-687a-11ea-92a4-e62adf05d1c2.png)

Note that the same fitting method is used for these two method with identical cutoff and other parameters. Similar issue is also occur for AlN example, where small negative frequency appear near gamma point which disappear within alamode code)..

Also it is possible to invoke phonopy-alm interface with command line?

This seems a fit strange to be and I am not able to identify the source of this difference... Any pointers will be helpful.

Thank for your time/

Thanks,
Alex

**Comment by atztogo** [comment]
I discussed with @ttadano a bit (now we work in a few tens of metres 3 dimensionally). We doubt how you set cutoff in phonopy&ALM because it's not well written in the documentation of phonopy. We want to make sure how you ran your calculations.

For example (you may try with NaCl example of phonopy),
```
phonopy --alm --dim 2 2 2 -c POSCAR --cutoff-radius 4 -v
```
doesn't set cutoff for ALM. But
```
phonopy --alm --dim 2 2 2 -c POSCAR --fc-calculator-options cutoff=4 -v
```
works for ALM. The option `--fc-calculator-options` is not written on the documentation of phonopy. I am very sorry! On this, you can find some information in the source code [here](https://github.com/phonopy/phonopy/blob/02e31d5998de0a9b664b67968bb511e21c400574/phonopy/interface/alm.py#L181). Once force constants are created by, e.g.,
```
phonopy --alm --dim 2 2 2 -c POSCAR --fc-calculator-options cutoff=4 -v --writefc
```
no need to use alm again in running phonopy by reading the force constants.
```
phonopy --dim 2 2 2 -c POSCAR -v --readfc --band auto -p
```

Togo

**Comment by akentphonon** [comment]
Thank you Dr. Toga and Dr . Tandano. This seems to work perfectly. 

But the issue is occurs when I use ALM library in python script as shown in AlN example. I tried increasing the cutoff but the dispersion does not change.

This seems to give small negative frequencies near zone center.


import h5py
import numpy as np
from alm import ALM

with open("POSCAR_AlN") as f:
    lines = f.readlines()
[lines.pop(0) for i in range(2)]
[lines.pop(3) for i in range(3)]
vals = np.array([np.fromstring(l, dtype='double', sep=' ') for l in lines])
lavec = vals[:3]
xcoord = vals[3:]
numbers = [13, ] * 36 + [7, ] * 36
natom = len(numbers)

dfset = np.loadtxt("DFSET_AlN").reshape((-1, natom, 6))
displacements = dfset[:, :, :3]
forces = dfset[:, :, 3:]
cutoff_radii = [np.ones((2, 2)) * -1, np.ones((2, 2)) * 4]

with ALM(lavec, xcoord, numbers, verbosity=1) as alm:
    alm.displacements = displacements
    alm.forces = forces
    alm.define(2, cutoff_radii=cutoff_radii)
    alm.optimize()
    fc2 = np.zeros((natom, natom, 3, 3), dtype='double', order='C')
    fc3 = np.zeros((natom, natom, natom, 3, 3, 3), dtype='double', order='C')
    for fc, indices in zip(*alm.get_fc(1, mode='all')):
        v1, v2 = indices // 3
        c1, c2 = indices % 3
        fc2[v1, v2, c1, c2] = fc
    for fc, indices in zip(*alm.get_fc(2, mode='all')):
        v1, v2, v3 = indices // 3
        c1, c2, c3 = indices % 3
        fc3[v1, v2, v3, c1, c2, c3] = fc
    with h5py.File('fc.hdf5', 'w') as w:
        w.create_dataset('fc2', data=fc2, compression='gzip')
        w.create_dataset('fc3', data=fc3, compression='gzip')



Any thought will be helpful.

Thanks

Best
Alex

**Comment by atztogo** [comment]
Indentation of your script is broken. Could you fix it?

**Comment by akentphonon** [comment]
Sorry about that. I reattached the script now.

You can also find this script at 

https://github.com/ttadano/ALM/blob/develop/docs/python-module.rst


`import h5py
import numpy as np
from alm import ALM

with open("POSCAR_AlN") as f:
    lines = f.readlines()
[lines.pop(0) for i in range(2)]
[lines.pop(3) for i in range(3)]
vals = np.array([np.fromstring(l, dtype='double', sep=' ') for l in lines])
lavec = vals[:3]
xcoord = vals[3:]
numbers = [13, ] * 36 + [7, ] * 36
natom = len(numbers)

dfset = np.loadtxt("DFSET_AlN").reshape((-1, natom, 6))
displacements = dfset[:, :, :3]
forces = dfset[:, :, 3:]

cutoff_radii = [np.ones((2, 2)) * -1, np.ones((2, 2)) * 7]
#cutoff_radii = [np.ones((2, 2)) * -1]

with ALM(lavec, xcoord, numbers, verbosity=1) as alm:
    alm.displacements = displacements
    alm.forces = forces
    alm.define(2, cutoff_radii=cutoff_radii)
    alm.optimize()

    fc2 = np.zeros((natom, natom, 3, 3), dtype='double', order='C')
    fc3 = np.zeros((natom, natom, natom, 3, 3, 3), dtype='double', order='C')
    for fc, indices in zip(*alm.get_fc(1, mode='all')):
        v1, v2 = indices // 3
        c1, c2 = indices % 3
        fc2[v1, v2, c1, c2] = fc
    for fc, indices in zip(*alm.get_fc(2, mode='all')):
        v1, v2, v3 = indices // 3
        c1, c2, c3 = indices % 3
        fc3[v1, v2, v3, c1, c2, c3] = fc
    with h5py.File('fc2.hdf5', 'w') as w:
        w.create_dataset('fc2', data=fc2, compression='gzip')
    with h5py.File('fc3.hdf5', 'w') as w:
        w.create_dataset('fc3', data=fc3, compression='gzip')
`

Thanks.

**Comment by atztogo** [comment]
If I fit only to fc2 by the script below, I don't see a big issue. How do you use ALAMODE?

```
import h5py
import numpy as np
from alm import ALM

with open("POSCAR_AlN") as f:
    lines = f.readlines()
[lines.pop(0) for i in range(2)]
[lines.pop(3) for i in range(3)]
vals = np.array([np.fromstring(l, dtype='double', sep=' ') for l in lines])
lavec = vals[:3]
xcoord = vals[3:]
numbers = [13, ] * 36 + [7, ] * 36
natom = len(numbers)

dfset = np.loadtxt("DFSET_AlN").reshape((-1, natom, 6))
displacements = dfset[:, :, :3]
forces = dfset[:, :, 3:]

# cutoff_radii = [np.ones((2, 2)) * -1, np.ones((2, 2)) * 4]
cutoff_radii = [np.ones((2, 2)) * -1,]

with ALM(lavec, xcoord, numbers, verbosity=1) as alm:
    alm.displacements = displacements
    alm.forces = forces
    alm.define(1, cutoff_radii=cutoff_radii)
    alm.optimize()

    fc2 = np.zeros((natom, natom, 3, 3), dtype='double', order='C')
    # fc3 = np.zeros((natom, natom, natom, 3, 3, 3), dtype='double', order='C')
    for fc, indices in zip(*alm.get_fc(1, mode='all')):
        v1, v2 = indices // 3
        c1, c2 = indices % 3
        fc2[v1, v2, c1, c2] = fc
    # for fc, indices in zip(*alm.get_fc(2, mode='all')):
    #     v1, v2, v3 = indices // 3
    #     c1, c2, c3 = indices % 3
    #     fc3[v1, v2, v3, c1, c2, c3] = fc
    with h5py.File('fc.hdf5', 'w') as w:
        w.create_dataset('fc2', data=fc2, compression='gzip')
        # w.create_dataset('fc3', data=fc3, compression='gzip')
```

```
% ln -s fc.hdf5 force_constants.hdf5
% phonopy --dim 1 1 1 --pa auto -c POSCAR_AlN --readfc --readfc-format hdf5 --band auto -p
```
![Figure_1](https://user-images.githubusercontent.com/953404/77053332-8bc2a900-6a11-11ea-99db-a36854e63da1.png)

**Comment by akentphonon** [comment]
Thank prof. Togo. I was mixing up Bohr (used in alamode),  and Angstrom (in Phonopy) in the cutoff between the two code. 

Now after accounting for this the problem is resolved.  I will close this issue for now.

Thank you so much for your help..

best,
Alex

**Comment by atztogo** [comment]
Interoperability problem. We should prepare a method to write force constants (e.g. in hdf5) with the information of physical units and each code will need to consistency check or unit conversion internally. But this will not be easy to get agreement in a short time. For the meantime, I modified phonopy to show unit of length in the develop branch.
