### ISSUE TITLE
setting cutoff

### ISSUE THREAD

**Issue by alinelena** [ttadano/ALM#35]
I am trying to setup some cutoff in the python version but somehow I fail to find docs about

&cutoff
*-* 8.0 4.0
H-C 8.0 4.0
H-O 8.0 4.0
H-Zn 8.0 4.0
C-O 8.0 4.0
C-Zn 8.0 4.0
O-Zn 8.0 4.0
/

any help appreciated.

**Comment by atztogo** [comment]
Here you can find some information, https://alm.readthedocs.io/en/develop/python-module.html#
You can also refer the docstrings:
```
In [1]: import alm
In [2]: from alm import ALM
In [3]: help(ALM)
```

**Comment by alinelena** [comment]
thank you for you answer... I have already read that bit of  documentation and it is pretty opaque for me

```
 |      cutoff_radii : array_like, default = None
 |          Cutoff radii defined for each order.
 |          When a negative value is provided, the cutoff radius is not used.
 |          dtype='double'
 |          shape=(maxorder, num_elems, num_elems)

```

i try to see the elements map but I fail.
also kind_names seems to be indexed on atomic numbers, what happens when you deal with forcefields where you tend to have more than one kind for the same element.

**Comment by atztogo** [comment]
I don't understand what you mean. Can you describe more details?

**Comment by ttadano** [comment]
In the python version, you need to specify the cutoff radii between all elements; a wildcard (*) is not available. Assuming that you have 5 elements and consider harmonic and third-order terms, you need to prepare `cutoff_radii` as
```
cutoff_harmonic = np.ones((5,5)) * -1
cutoff_cubic = np.ones((5,5)) * 4.0

# update cutoff values if necessary
cutoff_harmonic[0, 1] = 4.0
cutoff_harmonic[1, 0] = 4.0
cutoff_cubic[0, 1] = 2.0
cutoff_cubic[1, 0] = 2.0

cutoff_radii = [cutoff_harmonic, cutoff_cubic]
```

> also kind_names seems to be indexed on atomic numbers, what happens when you deal with forcefields where you tend to have more than one kind for the same element.

The element number is somewhat arbitrary in ALM because physical information of the atomic element is not used in ALM. They are used just to symmetrize force constants.

**Comment by alinelena** [comment]
sorry I did not express myself properly... 
I read a series of coordinates

```
C1 x  y z
H
C2
C2
O
O
Zn
H
```
will index o be C1 1, H 2 C2 3 O and so on? based on the order they appear in the coordinates?

practically I am having a working set of input files for alm and anphon and I try to convert the alm part to alm.py. in  long term the expectation is to see if I can obtain the same thermal conductivity from anphon and phonopy3

**Comment by ttadano** [comment]
> will index o be C1 1, H 2 C2 3 O and so on? based on the order they appear in the coordinates?

Yes, exactly.

**Comment by alinelena** [comment]
thank you that is helpful.

**Comment by ttadano** [comment]
Close this inactive issue. Please reopen it if necessary.
